name: Java CI with Maven

on:
  push:
    branches: [ "master" ] # 触发分支
  pull_request:
    branches: [ "master" ] # 触发分支

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # 选择一个Java发行版
        cache: maven # 缓存m2仓库以加速构建
    - name: Build with Maven
      run: export TZ=Asia/Shanghai; mvn -B clean package -pl spec --file pom.xml
    - name: Run JUnit tests
      run: export TZ=Asia/Shanghai; mvn -B verify -pl spec --file pom.xml
    - name: Collect Test Results
      run: |
        mkdir -p ./test-results
        for d in $(find . -type d -name "surefire-reports"); do
          cp $d/*.xml ./test-results/
        done
      shell: bash
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          spec/target/surefire-reports/
          client/**/target/surefire-reports
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          test-results/**/*.xml
          test-results/**/*.trx
          test-results/**/*.json
